{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stepca.fullname" . }}-secrets
  labels: {{- include "stepca.labels" . | nindent 4 }}
type: Opaque
stringData:
  root_ca_password.txt: {{ .Values.secrets.rootPassword | quote }}
  intermediate_ca_password.txt: {{ .Values.secrets.intermediatePassword | quote }}
  ra_password.txt: {{ .Values.secrets.raPassword | quote }}
{{- end }}
